/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.ComplexMarkupWithLanguage;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.BasicAnnotation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BasicAnnotationValidator {
	boolean validate();

	boolean validateText(EList<ComplexMarkupWithLanguage> value);
	boolean validateCombinedText(EList<ComplexMarkupWithLanguage> value);
	boolean validateAppendAnnotationId(String value);
	boolean validateGraphicLinkId(String value);
	boolean validateId(String value);
	boolean validatePrependAnnotationId(String value);
	boolean validateSortKey(String value);
}
