/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import java.math.BigInteger;

import javax.xml.datatype.XMLGregorianCalendar;

import org.openhealthtools.mdht.emf.hl7.mif2.CodingStrengthKind;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.ContextBinding}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContextBindingValidator {
	boolean validate();

	boolean validateBindingPriority(BigInteger value);
	boolean validateBindingRealmName(String value);
	boolean validateCodingStrength(CodingStrengthKind value);
	boolean validateConceptDomain(String value);
	boolean validateEffectiveDate(XMLGregorianCalendar value);
	boolean validateExpiryDate(XMLGregorianCalendar value);
	boolean validateIgnoredValueSet(String value);
	boolean validateMinimumValueSet(String value);
	boolean validateSortKey(String value);
	boolean validateValueSet(String value);
	boolean validateVersionDate(XMLGregorianCalendar value);
	boolean validateVersionTime(XMLGregorianCalendar value);
}
