/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import javax.xml.datatype.XMLGregorianCalendar;

import org.openhealthtools.mdht.emf.w3c.xhtml.Flow;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.HistoryItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HistoryItemValidator {
	boolean validate();

	boolean validateDescription(Flow value);
	boolean validateDateTime(XMLGregorianCalendar value);
	boolean validateId(String value);
	boolean validateIsBackwardCompatibleChange(boolean value);
	boolean validateIsSubstantiveChange(boolean value);
	boolean validateResponsiblePersonName(String value);
}
