/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.ComplexMarkupWithLanguage;
import org.openhealthtools.mdht.emf.hl7.mif2.PackageOrArtifactRef;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.TestSystem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TestSystemValidator {
	boolean validate();

	boolean validatePreConditions(ComplexMarkupWithLanguage value);
	boolean validateExpectedPostConditions(ComplexMarkupWithLanguage value);
	boolean validateTestedApplicationRole(EList<PackageOrArtifactRef> value);
	boolean validateTestedProfile(EList<PackageOrArtifactRef> value);
	boolean validateName(String value);
	boolean validateUnderTest(boolean value);
}
