<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rim"
    nsURI="http://www.openhealthtools.org/mdht/uml/hl7/rim" nsPrefix="rim">
  <eClassifiers xsi:type="ecore:EClass" name="Act" abstract="true" eSuperTypes="#//InfrastructureRoot">
    <eOperations name="getClassCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getMoodCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getNegationInd" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eOperations name="getParticipations" ordered="false" upperBound="-1" eType="#//Participation"/>
    <eOperations name="getOutboundRelationships" ordered="false" upperBound="-1" eType="#//ActRelationship"/>
    <eOperations name="getInboundRelationships" ordered="false" upperBound="-1" eType="#//ActRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfrastructureRoot" abstract="true">
    <eOperations name="getRealmCodes" ordered="false" upperBound="-1" eType="ecore:EClass ../../org.openhealthtools.mdht.uml.hl7.datatypes/model/datatypes.ecore#//CS"/>
    <eOperations name="getTypeId" ordered="false" eType="ecore:EClass ../../org.openhealthtools.mdht.uml.hl7.datatypes/model/datatypes.ecore#//II"/>
    <eOperations name="getTemplateIds" ordered="false" upperBound="-1" eType="ecore:EClass ../../org.openhealthtools.mdht.uml.hl7.datatypes/model/datatypes.ecore#//II"/>
    <eOperations name="getNullFlavor" ordered="false" eType="ecore:EEnum ../../org.openhealthtools.mdht.uml.hl7.vocab/model/vocab.ecore#//NullFlavor"/>
    <eOperations name="isNullFlavorDefined" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isNullFlavorUndefined" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="hasContent" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isDefined" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="featureName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="isClassCodeDefined" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.isDefined('classCode')"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/uml2/1.1.0/GenModel">
        <details key="body" value="self.isDefined('classCode')"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isTypeCodeDefined" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.isDefined('typeCode')"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/uml2/1.1.0/GenModel">
        <details key="body" value="self.isDefined('typeCode')"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isContextControlCodeDefined" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.isDefined('contextControlCode')"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/uml2/1.1.0/GenModel">
        <details key="body" value="self.isDefined('contextControlCode')"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isDeterminerCodeDefined" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.isDefined('determinerCode')"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/uml2/1.1.0/GenModel">
        <details key="body" value="self.isDefined('determinerCode')"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isMoodCodeDefined" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.isDefined('moodCode')"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/uml2/1.1.0/GenModel">
        <details key="body" value="self.isDefined('moodCode')"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participation" abstract="true" eSuperTypes="#//InfrastructureRoot">
    <eOperations name="getTypeCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getAct" ordered="false" lowerBound="1" eType="#//Act"/>
    <eOperations name="getRole" ordered="false" lowerBound="1" eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true" eSuperTypes="#//InfrastructureRoot">
    <eOperations name="getClassCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getPlayer" ordered="false" eType="#//Entity"/>
    <eOperations name="getScoper" ordered="false" eType="#//Entity"/>
    <eOperations name="getParticipations" ordered="false" upperBound="-1" eType="#//Participation"/>
    <eOperations name="getOutboundLinks" ordered="false" upperBound="-1" eType="#//RoleLink"/>
    <eOperations name="getInboundLinks" ordered="false" upperBound="-1" eType="#//RoleLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true" eSuperTypes="#//InfrastructureRoot">
    <eOperations name="getClassCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getDeterminerCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getPlayedRoles" ordered="false" upperBound="-1" eType="#//Role"/>
    <eOperations name="getScopedRoles" ordered="false" upperBound="-1" eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleLink" abstract="true" eSuperTypes="#//InfrastructureRoot">
    <eOperations name="getTypeCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getTarget" ordered="false" lowerBound="1" eType="#//Role"/>
    <eOperations name="getSource" ordered="false" lowerBound="1" eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActRelationship" abstract="true" eSuperTypes="#//InfrastructureRoot">
    <eOperations name="getTypeCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getTarget" ordered="false" lowerBound="1" eType="#//Act"/>
    <eOperations name="getSource" ordered="false" lowerBound="1" eType="#//Act"/>
  </eClassifiers>
</ecore:EPackage>
