/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.w3c.xhtml.validation;

import org.openhealthtools.mdht.emf.w3c.xhtml.ParamName;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.w3c.xhtml.Param}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParamValidator {
	boolean validate();

	boolean validateName(ParamName value);
	boolean validateValue(String value);
}
