/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.w3c.xhtml.validation;

import java.math.BigInteger;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.w3c.xhtml.Caption;
import org.openhealthtools.mdht.emf.w3c.xhtml.Col;
import org.openhealthtools.mdht.emf.w3c.xhtml.Colgroup;
import org.openhealthtools.mdht.emf.w3c.xhtml.MifClassType;
import org.openhealthtools.mdht.emf.w3c.xhtml.StyleSheet;
import org.openhealthtools.mdht.emf.w3c.xhtml.TFrame;
import org.openhealthtools.mdht.emf.w3c.xhtml.TRules;
import org.openhealthtools.mdht.emf.w3c.xhtml.Tbody;
import org.openhealthtools.mdht.emf.w3c.xhtml.Tfoot;
import org.openhealthtools.mdht.emf.w3c.xhtml.Thead;
import org.openhealthtools.mdht.emf.w3c.xhtml.Tr;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.w3c.xhtml.Table}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TableValidator {
	boolean validate();

	boolean validateCaption(Caption value);
	boolean validateCol(EList<Col> value);
	boolean validateColgroup(EList<Colgroup> value);
	boolean validateThead(Thead value);
	boolean validateTfoot(Tfoot value);
	boolean validateTbody(EList<Tbody> value);
	boolean validateTr(EList<Tr> value);
	boolean validateBorder(BigInteger value);
	boolean validateCellpadding(String value);
	boolean validateCellspacing(String value);
	boolean validateClass(MifClassType value);
	boolean validateFrame(TFrame value);
	boolean validateHl7Id(String value);
	boolean validateLang(String value);
	boolean validateRules(TRules value);
	boolean validateStyle(StyleSheet value);
	boolean validateWidth(String value);
}
