<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="codesystemversion"
    nsURI="http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion" nsPrefix="codesystemversion">
  <eClassifiers xsi:type="ecore:EClass" name="CodeSystemVersionCatalogEntry" eSuperTypes="core.ecore#//ResourceVersionDescription">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&#xA;  &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>CodeSystemVersion&lt;/i> is a collection of assertions about one or more entities. If the &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>state&lt;/i> of a &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>CodeSystemVersion&lt;/i> is &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>Final &lt;/i>the set of assertions made the resource is fixed, meaning&#xA;&#x9;&#x9;&#x9;&#x9;that if one knows the &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>documentURI&lt;/i> assigned to the version and the specific &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>sourceAndNotation&lt;/i> from which the version instance was derived, the set of assertions is known as well."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="CodeSystemVersionCatalogEntry"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionOf" lowerBound="1"
        eType="ecore:EClass core.ecore#//CodeSystemReference" containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="the name, URI and, if supported by the service, link to the code system that this version represents."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="versionOf"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass core.ecore#//CodeSystemVersionReference" containment="true"
        resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="a reference to a code system version whose assertions are included as part this code system version. "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="imports"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultLanguage" eType="ecore:EClass core.ecore#//LanguageReference"
        containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="the default spoken or written language used in this version"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="defaultLanguage"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedLanguage" upperBound="-1"
        eType="ecore:EClass core.ecore#//LanguageReference" containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="all languages recognized by this particular code system version"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="supportedLanguage"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entityDescriptions" eType="ecore:EDataType core.ecore#//EntityDirectoryURI">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="a DirectoryURI that resolves to the set of all entities and their descriptions asserted by this code system version. This attribute will only be present if and only if the service implementation&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;supports the &lt;b xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>EntityQuery&lt;/b> service profile."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="entityDescriptions"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associations" eType="ecore:EDataType core.ecore#//AssociationDirectoryURI">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="a &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>DirectoryURI&lt;/i> that,resolves to a a list of all associations asserted by this particular code system version"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="associations"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classes" eType="ecore:EDataType core.ecore#//EntityDirectoryURI">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="a &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>DirectoryURI&lt;/i> that resolves to the set of &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>EntityDescriptions &lt;/i>that are of type owl:Class within this code system. Will only be present in code systems that represent&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;ontologies."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="classes"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roles" eType="ecore:EDataType core.ecore#//EntityDirectoryURI">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="a &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>DirectoryURI&lt;/i> that resolves to the set of &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>EntityDescriptions &lt;/i>that are of type owl:ObjectProperty or owl:DataProperty within this code system. Will only be present in code systems&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;that represent ontologies."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="roles"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="individuals" eType="ecore:EDataType core.ecore#//EntityDirectoryURI">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="a &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>DirectoryURI&lt;/i> that resolves to the set of &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>EntityDescriptions &lt;/i>that are of type owl:Individual within this code system. Will only be present in code systems that represent&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;ontologies."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="individuals"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeSystemVersionName"
        lowerBound="1" eType="ecore:EDataType core.ecore#//CodeSystemVersionName">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="an identifier that uniquely names this particular code system version within the context of the CTS&lt;sub xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>2&lt;/sub> service instance."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="codeSystemVersionName"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeSystemVersionCatalogEntryDirectory"
      eSuperTypes="core.ecore#//Directory">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A directory of &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>CodeSystemVersion&lt;/i> resources that meet a specified criteria."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="CodeSystemVersionCatalogEntryDirectory"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" upperBound="-1"
        eType="#//CodeSystemVersionCatalogEntrySummary" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="entry"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeSystemVersionCatalogEntryList" eSuperTypes="core.ecore#//Directory">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A collection of complete &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>CodeSystemVersion&lt;/i> resources that meet a specified criteria."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="CodeSystemVersionCatalogEntryList"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" upperBound="-1"
        eType="#//CodeSystemVersionCatalogEntryListEntry" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="entry"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeSystemVersionCatalogEntryListEntry"
      eSuperTypes="core.ecore#//DirectoryEntry">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An instance of &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>CodeSystemVersion&lt;/i> that meets a specified filter criteria."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="CodeSystemVersionCatalogEntryListEntry"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" lowerBound="1" eType="#//CodeSystemVersionCatalogEntry"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="entry"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeSystemVersionCatalogEntryMsg" eSuperTypes="core.ecore#//Message">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>CodeSystemVersionCatalogEntry&lt;/i> read from a service instance."/>
    </eAnnotations>
    <eAnnotations>
      <details key="appinfo" value="PSM"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="CodeSystemVersionCatalogEntryMsg"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeSystemVersionCatalogEntry"
        lowerBound="1" eType="#//CodeSystemVersionCatalogEntry" containment="true"
        resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="codeSystemVersionCatalogEntry"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeSystemVersionCatalogEntrySummary"
      eSuperTypes="core.ecore#//ResourceVersionDescriptionDirectoryEntry">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A synopsis of a &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>CodeSystemVersion&lt;/i> along with information about how to access the complete resource."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="CodeSystemVersionCatalogEntrySummary"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionOf" lowerBound="1"
        eType="ecore:EClass core.ecore#//CodeSystemReference" containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="the name, URI and, if supported by the service, link to the code system that this version represents."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="versionOf"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeSystemVersionTag" upperBound="-1"
        eType="ecore:EClass core.ecore#//VersionTagReference" containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="the tag(s) assigned to this version by the service provider. &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>codeSystemVersionTag&lt;/i> identifies any roles that this version plays within the workflow of the current provider. As an example,&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;a provider might assign the tags of &quot;production&quot; and &quot;current&quot; to a given code system version. With the exception of &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>CURRENT&lt;/i> the semantics of VersionTag are determined by the service&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;provider."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="codeSystemVersionTag"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeSystemVersionName"
        lowerBound="1" eType="ecore:EDataType core.ecore#//CodeSystemVersionName">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="an identifier that uniquely names this particular code system version within the context of the CTS&lt;sub xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>2&lt;/sub> service instance."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="codeSystemVersionName"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value=""/>
      <details key="kind" value="mixed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="elementWildcard"/>
        <details key="name" value=":mixed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xMLNSPrefixMap" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
        transient="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="xmlns:prefix"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xSISchemaLocation" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
        transient="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="xsi:schemaLocation"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeSystemVersionCatalogEntry"
        upperBound="-2" eType="#//CodeSystemVersionCatalogEntry" volatile="true" transient="true"
        derived="true" containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xA;  &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>CodeSystemVersion&lt;/i> is a collection of assertions about one or more entities. If the &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>state&lt;/i> of a &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>CodeSystemVersion&lt;/i> is &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>Final &lt;/i>the set of assertions made the resource is fixed, meaning&#xA;&#x9;&#x9;&#x9;&#x9;that if one knows the &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>documentURI&lt;/i> assigned to the version and the specific &lt;i xmlns=&quot;http://schema.omg.org/spec/CTS2/1.0/CodeSystemVersion&quot;>sourceAndNotation&lt;/i> from which the version instance was derived, the set of assertions is known as well."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="CodeSystemVersionCatalogEntry"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeSystemVersionCatalogEntryDirectory"
        upperBound="-2" eType="#//CodeSystemVersionCatalogEntryDirectory" volatile="true"
        transient="true" derived="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="CodeSystemVersionCatalogEntryDirectory"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeSystemVersionCatalogEntryList"
        upperBound="-2" eType="#//CodeSystemVersionCatalogEntryList" volatile="true"
        transient="true" derived="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="CodeSystemVersionCatalogEntryList"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeSystemVersionCatalogEntryMsg"
        upperBound="-2" eType="#//CodeSystemVersionCatalogEntryMsg" volatile="true"
        transient="true" derived="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="CodeSystemVersionCatalogEntryMsg"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
