/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import java.math.BigInteger;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.openhealthtools.mdht.emf.hl7.mif2.AddElementContent;
import org.openhealthtools.mdht.emf.hl7.mif2.AttributeContent;
import org.openhealthtools.mdht.emf.hl7.mif2.MifContent;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.AddElementContent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AddElementContentValidator {
	boolean validate();

	boolean validateReplacementContent(MifContent value);
	boolean validateAddElements(FeatureMap value);
	boolean validateAddAttribute(EList<AttributeContent> value);
	boolean validateAddElement(EList<AddElementContent> value);
	boolean validateAfterElementName(String value);
	boolean validateAfterRepetition(BigInteger value);
	boolean validateName(String value);
}
