/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.CodeSupplement;
import org.openhealthtools.mdht.emf.hl7.mif2.ConceptProperty;
import org.openhealthtools.mdht.emf.hl7.mif2.ConceptRelationship;
import org.openhealthtools.mdht.emf.hl7.mif2.ConceptSupplementAnnotations;
import org.openhealthtools.mdht.emf.hl7.mif2.PrintName;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.ConceptSupplement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConceptSupplementValidator {
	boolean validate();

	boolean validateAnnotations(ConceptSupplementAnnotations value);
	boolean validateSupplementalConceptRelationship(EList<ConceptRelationship> value);
	boolean validateSupplementalConceptProperty(EList<ConceptProperty> value);
	boolean validatePrintName(EList<PrintName> value);
	boolean validateCodeSupplement(EList<CodeSupplement> value);
	boolean validateCode(String value);
}
