/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.ClassGraphicInformation;
import org.openhealthtools.mdht.emf.hl7.mif2.GraphEdgeGraphicInformation;
import org.openhealthtools.mdht.emf.hl7.mif2.NodeWithConnectionGraphicInformation;
import org.openhealthtools.mdht.emf.hl7.mif2.StaticModelDiagramPresentationKind;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.StaticPackageDiagramGraphicInformation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StaticPackageDiagramGraphicInformationValidator {
	boolean validate();

	boolean validateEntryPoint(EList<NodeWithConnectionGraphicInformation> value);
	boolean validateClass(EList<ClassGraphicInformation> value);
	boolean validateAssociation(EList<GraphEdgeGraphicInformation> value);
	boolean validateGeneralization(EList<GraphEdgeGraphicInformation> value);
	boolean validateAnnotation(EList<NodeWithConnectionGraphicInformation> value);
	boolean validatePresentation(StaticModelDiagramPresentationKind value);
}
