/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.BusinessName;
import org.openhealthtools.mdht.emf.hl7.mif2.TransitionAnnotations;
import org.openhealthtools.mdht.emf.hl7.mif2.TransitionDerivation;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.Transition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransitionValidator {
	boolean validate();

	boolean validateBusinessName(EList<BusinessName> value);
	boolean validateAnnotations(TransitionAnnotations value);
	boolean validateDerivedFrom(EList<TransitionDerivation> value);
	boolean validateEndStateName(String value);
	boolean validateName(String value);
	boolean validateSortKey(String value);
	boolean validateStartStateName(String value);
}
