/*******************************************************************************
 * Copyright (c) 2006, 2009 David A Carlson
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     David A Carlson (XMLmodeling.com) - initial API and implementation
 *******************************************************************************/
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.openhealthtools.mdht.emf.hl7.mif2.GlobalApplicationRole;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalConformanceProfile;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalDatatypeModelLibrary;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalDerivedStaticModel;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalDomainAnalysisModel;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalDomainInstanceExample;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalFreehandDocument;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalGenericPackage;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalInteraction;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalInteractionProfile;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalPublicationPackage;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalSerializedStaticModel;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalStaticModel;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalStaticModelInterfacePackage;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalStoryboard;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalStructuredDocument;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalTestScenario;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalTriggerEvent;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalVocabularyModel;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.PackageContent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PackageContentValidator {
	boolean validate();

	boolean validateGroup(FeatureMap value);

	boolean validateFreehandDocument(EList<GlobalFreehandDocument> value);

	boolean validateDomainAnalysisModel(EList<GlobalDomainAnalysisModel> value);

	boolean validateDomainInstanceExample(EList<GlobalDomainInstanceExample> value);

	boolean validateStoryboard(EList<GlobalStoryboard> value);

	boolean validateDatatypeModelLibrary(EList<GlobalDatatypeModelLibrary> value);

	boolean validateStaticModelInterfacePackage(EList<GlobalStaticModelInterfacePackage> value);

	boolean validateVocabularyModel(EList<GlobalVocabularyModel> value);

	boolean validateStaticModel(EList<GlobalStaticModel> value);

	boolean validateSerializedStaticModel(EList<GlobalSerializedStaticModel> value);

	boolean validateDerivedStaticModel(EList<GlobalDerivedStaticModel> value);

	boolean validateStructuredDocument(EList<GlobalStructuredDocument> value);

	boolean validateTriggerEvent(EList<GlobalTriggerEvent> value);

	boolean validateInteraction(EList<GlobalInteraction> value);

	boolean validateApplicationRole(EList<GlobalApplicationRole> value);

	boolean validateInteractionProfile(EList<GlobalInteractionProfile> value);

	boolean validateConformanceProfile(EList<GlobalConformanceProfile> value);

	boolean validateTestScenario(EList<GlobalTestScenario> value);

	boolean validatePublication(EList<GlobalPublicationPackage> value);

	boolean validatePackage(EList<GlobalGenericPackage> value);
}
