/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.CodeTranslation;
import org.openhealthtools.mdht.emf.hl7.mif2.CodeTranslationCollectionAnnotations;
import org.openhealthtools.mdht.emf.hl7.mif2.Header;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.CodeTranslationCollection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CodeTranslationCollectionValidator {
	boolean validate();

	boolean validateHeader(Header value);
	boolean validateAnnotations(CodeTranslationCollectionAnnotations value);
	boolean validateTranslation(EList<CodeTranslation> value);
	boolean validateTitle(String value);
}
