/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import java.math.BigInteger;

import java.util.List;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.AttributeAnnotations;
import org.openhealthtools.mdht.emf.hl7.mif2.AttributeDerivation;
import org.openhealthtools.mdht.emf.hl7.mif2.AttributeProperty;
import org.openhealthtools.mdht.emf.hl7.mif2.BusinessName;
import org.openhealthtools.mdht.emf.hl7.mif2.DatatypeRef;
import org.openhealthtools.mdht.emf.hl7.mif2.UpdateModeKind;
import org.openhealthtools.mdht.emf.hl7.mif2.VocabularySpecification;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.Attribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeValidator {
	boolean validate();

	boolean validateBusinessName(EList<BusinessName> value);
	boolean validateAnnotations(AttributeAnnotations value);
	boolean validateDerivedFrom(EList<AttributeDerivation> value);
	boolean validateType(DatatypeRef value);
	boolean validateVocabulary(VocabularySpecification value);
	boolean validateProperty(EList<AttributeProperty> value);
	boolean validateExtensionOID(String value);
	boolean validateIsImmutable(boolean value);
	boolean validateMaximumMultiplicity(Object value);
	boolean validateMinimumMultiplicity(BigInteger value);
	boolean validateName(String value);
	boolean validateSortKey(String value);
	boolean validateUpdateModeDefault(UpdateModeKind value);
	boolean validateUpdateModesAllowed(List<UpdateModeKind> value);
}
