/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.Concept;
import org.openhealthtools.mdht.emf.hl7.mif2.SupportedConceptProperty;
import org.openhealthtools.mdht.emf.hl7.mif2.SupportedConceptRelationship;
import org.openhealthtools.mdht.emf.hl7.mif2.SupportedProperty;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.CodeSystemVersion}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CodeSystemVersionValidator {
	boolean validate();

	boolean validateSupportedConceptRelationship(EList<SupportedConceptRelationship> value);
	boolean validateSupportedConceptProperty(EList<SupportedConceptProperty> value);
	boolean validateSupportedCodeProperty(EList<SupportedProperty> value);
	boolean validateConcept(EList<Concept> value);
	boolean validateCompleteCodesIndicator(boolean value);
}
