<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rim"
    nsURI="http://www.openhealthtools.org/mdht/uml/hl7/rim" nsPrefix="rim">
  <eClassifiers xsi:type="ecore:EClass" name="RIMAct" abstract="true" eSuperTypes="#//RIMInfrastructureRoot">
    <eOperations name="getClassCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getMoodCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getNegationInd" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eOperations name="getParticipations" ordered="false" upperBound="-1" eType="#//RIMParticipation"/>
    <eOperations name="getOutboundRelationships" ordered="false" upperBound="-1" eType="#//RIMActRelationship"/>
    <eOperations name="getInboundRelationships" ordered="false" upperBound="-1" eType="#//RIMActRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RIMInfrastructureRoot" abstract="true">
    <eOperations name="getRealmCodes" ordered="false" upperBound="-1" eType="ecore:EClass ../../org.openhealthtools.mdht.uml.hl7.datatypes/model/datatypes.ecore#//CS"/>
    <eOperations name="getTypeId" ordered="false" eType="ecore:EClass ../../org.openhealthtools.mdht.uml.hl7.datatypes/model/datatypes.ecore#//II"/>
    <eOperations name="getTemplateIds" ordered="false" upperBound="-1" eType="ecore:EClass ../../org.openhealthtools.mdht.uml.hl7.datatypes/model/datatypes.ecore#//II"/>
    <eOperations name="getNullFlavor" ordered="false" eType="ecore:EEnum ../../org.openhealthtools.mdht.uml.hl7.vocab/model/vocab.ecore#//NullFlavor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RIMParticipation" abstract="true" eSuperTypes="#//RIMInfrastructureRoot">
    <eOperations name="getTypeCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getAct" ordered="false" lowerBound="1" eType="#//RIMAct"/>
    <eOperations name="getRole" ordered="false" lowerBound="1" eType="#//RIMRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RIMRole" abstract="true" eSuperTypes="#//RIMInfrastructureRoot">
    <eOperations name="getClassCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getPlayer" ordered="false" eType="#//RIMEntity"/>
    <eOperations name="getScoper" ordered="false" eType="#//RIMEntity"/>
    <eOperations name="getParticipations" ordered="false" upperBound="-1" eType="#//RIMParticipation"/>
    <eOperations name="getOutboundLinks" ordered="false" upperBound="-1" eType="#//RIMRoleLink"/>
    <eOperations name="getInboundLinks" ordered="false" upperBound="-1" eType="#//RIMRoleLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RIMEntity" abstract="true" eSuperTypes="#//RIMInfrastructureRoot">
    <eOperations name="getClassCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getDeterminerCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getPlayedRoles" ordered="false" upperBound="-1" eType="#//RIMRole"/>
    <eOperations name="getScopedRoles" ordered="false" upperBound="-1" eType="#//RIMRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RIMRoleLink" abstract="true" eSuperTypes="#//RIMInfrastructureRoot">
    <eOperations name="getTypeCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getTarget" ordered="false" lowerBound="1" eType="#//RIMRole"/>
    <eOperations name="getSource" ordered="false" lowerBound="1" eType="#//RIMRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RIMActRelationship" abstract="true"
      eSuperTypes="#//RIMInfrastructureRoot">
    <eOperations name="getTypeCode" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
    <eOperations name="getTarget" ordered="false" lowerBound="1" eType="#//RIMAct"/>
    <eOperations name="getSource" ordered="false" lowerBound="1" eType="#//RIMAct"/>
  </eClassifiers>
</ecore:EPackage>
