/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.w3c.xhtml.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.openhealthtools.mdht.emf.w3c.xhtml.AlignType;
import org.openhealthtools.mdht.emf.w3c.xhtml.MifClassType;
import org.openhealthtools.mdht.emf.w3c.xhtml.StyleSheet;
import org.openhealthtools.mdht.emf.w3c.xhtml.Td;
import org.openhealthtools.mdht.emf.w3c.xhtml.Th;
import org.openhealthtools.mdht.emf.w3c.xhtml.ValignType;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.w3c.xhtml.Tr}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TrValidator {
	boolean validate();

	boolean validateGroup(FeatureMap value);
	boolean validateTh(EList<Th> value);
	boolean validateTd(EList<Td> value);
	boolean validateAlign(AlignType value);
	boolean validateChar(String value);
	boolean validateCharoff(String value);
	boolean validateClass(MifClassType value);
	boolean validateLang(String value);
	boolean validateStyle(StyleSheet value);
	boolean validateValign(ValignType value);
}
