/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import java.math.BigInteger;

import javax.xml.datatype.XMLGregorianCalendar;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.ApprovalStatusKind;
import org.openhealthtools.mdht.emf.hl7.mif2.BallotSubmission;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.ApprovalInfo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ApprovalInfoValidator {
	boolean validate();

	boolean validateBallotSubmission(EList<BallotSubmission> value);
	boolean validateApprovalDate(XMLGregorianCalendar value);
	boolean validateApprovalStatus(ApprovalStatusKind value);
	boolean validateApprovingOrganization(String value);
	boolean validateBallotOccurrence(BigInteger value);
	boolean validateWithdrawalDate(XMLGregorianCalendar value);
}
