/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import javax.xml.datatype.XMLGregorianCalendar;

import org.openhealthtools.mdht.emf.hl7.mif2.ApprovalStatusKind;
import org.openhealthtools.mdht.emf.hl7.mif2.NegativeVoteResolutionKind;
import org.openhealthtools.mdht.emf.hl7.mif2.VoteKind;
import org.openhealthtools.mdht.emf.w3c.xhtml.Inline;


/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.BallotSubmission}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BallotSubmissionValidator {
	boolean validate();

	boolean validateVoterComments(Inline value);
	boolean validateResolution(NegativeVoteResolutionKind value);
	boolean validateStatus(ApprovalStatusKind value);
	boolean validateStatusDate(XMLGregorianCalendar value);
	boolean validateSubmissionId(String value);
	boolean validateSubmitterName(String value);
	boolean validateSubmitterOrganization(String value);
	boolean validateVote(VoteKind value);
}
