/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import java.math.BigDecimal;
import java.math.BigInteger;

import org.openhealthtools.mdht.emf.hl7.mif2.EffortQuantifierKind;
import org.openhealthtools.mdht.emf.w3c.xhtml.Flow;


/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.ChangeRequestEstimate}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ChangeRequestEstimateValidator {
	boolean validate();

	boolean validateDescription(Flow value);
	boolean validateCost(BigInteger value);
	boolean validateCostCurrency(String value);
	boolean validateEffort(BigDecimal value);
	boolean validateEffortQuantifier(EffortQuantifierKind value);
	boolean validateType(String value);
}
