/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.openhealthtools.mdht.emf.hl7.mif2.ExampleType;
import org.openhealthtools.mdht.emf.hl7.mif2.PackageOrArtifactRef;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.DocumentTest}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentTestValidator {
	boolean validate();

	boolean validateDocument(PackageOrArtifactRef value);
	boolean validateExampleContent(ExampleType value);
	boolean validateConsumingSystem(String value);
	boolean validateCreatingSystem(String value);
	boolean validateExampleFile(String value);
}
