/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.BallotComment;
import org.openhealthtools.mdht.emf.hl7.mif2.ChangeRequest;
import org.openhealthtools.mdht.emf.hl7.mif2.DeprecationInfo;
import org.openhealthtools.mdht.emf.hl7.mif2.FormalConstraint;
import org.openhealthtools.mdht.emf.hl7.mif2.Mapping;
import org.openhealthtools.mdht.emf.hl7.mif2.StaticExample;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.DomainAnalysisModelAppInfo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DomainAnalysisModelAppInfoValidator {
	boolean validate();

	boolean validateMapping(EList<Mapping> value);
	boolean validateFormalConstraint(EList<FormalConstraint> value);
	boolean validateStaticExample(EList<StaticExample> value);
	boolean validateBallotComment(EList<BallotComment> value);
	boolean validateChangeRequest(EList<ChangeRequest> value);
	boolean validateDeprecationInfo(DeprecationInfo value);
}
