/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.openhealthtools.mdht.emf.hl7.mif2.DomainAnalysisModelAppInfo;
import org.openhealthtools.mdht.emf.hl7.mif2.DomainAnalysisModelDocumentation;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.DomainAnalysisModelAnnotations}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DomainAnalysisModelAnnotationsValidator {
	boolean validate();

	boolean validateDocumentation(DomainAnalysisModelDocumentation value);
	boolean validateAppInfo(DomainAnalysisModelAppInfo value);
}
