/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.ArtifactRenderingStyleKind;
import org.openhealthtools.mdht.emf.hl7.mif2.ComplexMarkupWithLanguage;
import org.openhealthtools.mdht.emf.hl7.mif2.ItemFilter;
import org.openhealthtools.mdht.emf.hl7.mif2.PackageOrArtifactRef;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PublicationItemValidator {
	boolean validate();

	boolean validateItemReference(PackageOrArtifactRef value);
	boolean validateFilter(EList<ItemFilter> value);
	boolean validateFollowingText(EList<ComplexMarkupWithLanguage> value);
	boolean validateRenderingStyle(ArtifactRenderingStyleKind value);
}
