/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.BusinessName;
import org.openhealthtools.mdht.emf.hl7.mif2.ComplexMarkupWithLanguage;
import org.openhealthtools.mdht.emf.hl7.mif2.ContentsLevelKind;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PublicationBaseValidator {
	boolean validate();

	boolean validateBusinessName(EList<BusinessName> value);
	boolean validateRenderedText(EList<ComplexMarkupWithLanguage> value);
	boolean validatePrecedingText(EList<ComplexMarkupWithLanguage> value);
	boolean validateContentsLevel(ContentsLevelKind value);
	boolean validateName(String value);
	boolean validateRenderToLocation(String value);
	boolean validateSortKey(String value);
	boolean validateTitle(String value);
}
