/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.openhealthtools.mdht.emf.hl7.mif2.SerializedClass;
import org.openhealthtools.mdht.emf.hl7.mif2.SerializedCommonModelElementRef;
import org.openhealthtools.mdht.emf.hl7.mif2.StaticModelClassTemplateParameter;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.SerializedClasses}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SerializedClassesValidator {
	boolean validate();

	boolean validateClass(SerializedClass value);
	boolean validateCommonModelElementRef(SerializedCommonModelElementRef value);
	boolean validateTemplateParameter(StaticModelClassTemplateParameter value);
}
