/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.ApprovalInfo;
import org.openhealthtools.mdht.emf.hl7.mif2.LocalClassRef;
import org.openhealthtools.mdht.emf.hl7.mif2.StaticPackageDiagramGraphicInformation;
import org.openhealthtools.mdht.emf.hl7.mif2.SubjectAreaAnnotations;
import org.openhealthtools.mdht.emf.hl7.mif2.SubjectAreaPackage;
import org.openhealthtools.mdht.emf.w3c.xhtml.Img;


/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.SubjectAreaPackage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SubjectAreaPackageValidator {
	boolean validate();

	boolean validateApprovalInfo(ApprovalInfo value);
	boolean validateGraphicRepresentation(EList<StaticPackageDiagramGraphicInformation> value);
	boolean validateFigure(Img value);
	boolean validateAnnotations(SubjectAreaAnnotations value);
	boolean validateSubjectAreaPackage(EList<SubjectAreaPackage> value);
	boolean validateContainedClass(EList<LocalClassRef> value);
}
