/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.ConceptPropertyTypeKind;
import org.openhealthtools.mdht.emf.w3c.xhtml.Inline;


/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.SupportedProperty}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SupportedPropertyValidator {
	boolean validate();

	boolean validateDescription(Inline value);
	boolean validateEnumerationValue(EList<String> value);
	boolean validateDefaultValue(String value);
	boolean validateIsMandatoryIndicator(boolean value);
	boolean validatePropertyName(String value);
	boolean validateType(ConceptPropertyTypeKind value);
}
