/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.openhealthtools.mdht.emf.hl7.mif2.CodingStrengthKind;
import org.openhealthtools.mdht.emf.hl7.mif2.RevisionFrequencyKind;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.VocabularyValueSetBinding}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VocabularyValueSetBindingValidator {
	boolean validate();

	boolean validateCodingStrength(CodingStrengthKind value);
	boolean validateIgnoredValueSet(String value);
	boolean validateMinimumValueSet(String value);
	boolean validateRevisionFrequency(RevisionFrequencyKind value);
	boolean validateRootCode(String value);
}
