/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import java.math.BigDecimal;

import org.openhealthtools.mdht.emf.hl7.mif2.Dimension;
import org.openhealthtools.mdht.emf.hl7.mif2.NodeOrientation;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.GraphNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GraphNodeValidator {
	boolean validate();

	boolean validateSize(Dimension value);
	boolean validateIsHeightAutoSize(boolean value);
	boolean validateIsWidthAutoSize(boolean value);
	boolean validateNodeOrientation(NodeOrientation value);
	boolean validateTextWrappingWidth(BigDecimal value);
}
