/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.ComplexMarkupWithLanguage;
import org.openhealthtools.mdht.emf.hl7.mif2.Test;
import org.openhealthtools.mdht.emf.hl7.mif2.TestSystem;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.TestScenario}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TestScenarioValidator {
	boolean validate();

	boolean validateObjective(ComplexMarkupWithLanguage value);
	boolean validateTestSystem(EList<TestSystem> value);
	boolean validateTest(EList<Test> value);
}
