/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Publication Base</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * Defines elements common to all published items
 * UML: A stereotype on Model Element
 * <!-- end-model-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getBusinessName <em>Business Name</em>}</li>
 *   <li>{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getRenderedText <em>Rendered Text</em>}</li>
 *   <li>{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getPrecedingText <em>Preceding Text</em>}</li>
 *   <li>{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getContentsLevel <em>Contents Level</em>}</li>
 *   <li>{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getName <em>Name</em>}</li>
 *   <li>{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getRenderToLocation <em>Render To Location</em>}</li>
 *   <li>{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getSortKey <em>Sort Key</em>}</li>
 *   <li>{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getTitle <em>Title</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.openhealthtools.mdht.emf.hl7.mif2.Mif2Package#getPublicationBase()
 * @model abstract="true"
 *        extendedMetaData="name='PublicationBase' kind='elementOnly'"
 * @generated
 */
public interface PublicationBase extends EObject {
	/**
	 * Returns the value of the '<em><b>Business Name</b></em>' containment reference list.
	 * The list contents are of type {@link org.openhealthtools.mdht.emf.hl7.mif2.BusinessName}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * The business names associated with the element. CURRENT- 0..1
	 * UML: Tag value inherited from ModelElement
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Business Name</em>' containment reference list.
	 * @see org.openhealthtools.mdht.emf.hl7.mif2.Mif2Package#getPublicationBase_BusinessName()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='businessName' namespace='##targetNamespace'"
	 * @generated
	 */
	EList<BusinessName> getBusinessName();

	/**
	 * Returns the value of the '<em><b>Rendered Text</b></em>' containment reference list.
	 * The list contents are of type {@link org.openhealthtools.mdht.emf.hl7.mif2.ComplexMarkupWithLanguage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * A fully-rendered version of the content as pubMarkup.  (This may reference external graphics or other files.)
	 * UML: A tag on the PublicationBase stereotype
	 * Derive: Generated by full rendering software.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Rendered Text</em>' containment reference list.
	 * @see org.openhealthtools.mdht.emf.hl7.mif2.Mif2Package#getPublicationBase_RenderedText()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='renderedText' namespace='##targetNamespace'"
	 * @generated
	 */
	EList<ComplexMarkupWithLanguage> getRenderedText();

	/**
	 * Returns the value of the '<em><b>Preceding Text</b></em>' containment reference list.
	 * The list contents are of type {@link org.openhealthtools.mdht.emf.hl7.mif2.ComplexMarkupWithLanguage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Text to appear before the referenced element.
	 * UML: A tag on the PublicationBase stereotype
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Preceding Text</em>' containment reference list.
	 * @see org.openhealthtools.mdht.emf.hl7.mif2.Mif2Package#getPublicationBase_PrecedingText()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='precedingText' namespace='##targetNamespace'"
	 * @generated
	 */
	EList<ComplexMarkupWithLanguage> getPrecedingText();

	/**
	 * Returns the value of the '<em><b>Contents Level</b></em>' attribute.
	 * The default value is <code>"None"</code>.
	 * The literals are from the enumeration {@link org.openhealthtools.mdht.emf.hl7.mif2.ContentsLevelKind}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Indicates whether the business name for this element should appear in the detailed, summary or no contents
	 * UML: 
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Contents Level</em>' attribute.
	 * @see org.openhealthtools.mdht.emf.hl7.mif2.ContentsLevelKind
	 * @see #isSetContentsLevel()
	 * @see #unsetContentsLevel()
	 * @see #setContentsLevel(ContentsLevelKind)
	 * @see org.openhealthtools.mdht.emf.hl7.mif2.Mif2Package#getPublicationBase_ContentsLevel()
	 * @model default="None" unsettable="true"
	 *        extendedMetaData="kind='attribute' name='contentsLevel'"
	 * @generated
	 */
	ContentsLevelKind getContentsLevel();

	/**
	 * Sets the value of the '{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getContentsLevel <em>Contents Level</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Contents Level</em>' attribute.
	 * @see org.openhealthtools.mdht.emf.hl7.mif2.ContentsLevelKind
	 * @see #isSetContentsLevel()
	 * @see #unsetContentsLevel()
	 * @see #getContentsLevel()
	 * @generated
	 */
	void setContentsLevel(ContentsLevelKind value);

	/**
	 * Unsets the value of the '{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getContentsLevel <em>Contents Level</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isSetContentsLevel()
	 * @see #getContentsLevel()
	 * @see #setContentsLevel(ContentsLevelKind)
	 * @generated
	 */
	void unsetContentsLevel();

	/**
	 * Returns whether the value of the '{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getContentsLevel <em>Contents Level</em>}' attribute is set.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return whether the value of the '<em>Contents Level</em>' attribute is set.
	 * @see #unsetContentsLevel()
	 * @see #getContentsLevel()
	 * @see #setContentsLevel(ContentsLevelKind)
	 * @generated
	 */
	boolean isSetContentsLevel();

	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * A unique name for the element within the publication package allowing it to be referenced from elsewhere within the package or from other packages
	 * UML: ModelElement.name
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.openhealthtools.mdht.emf.hl7.mif2.Mif2Package#getPublicationBase_Name()
	 * @model dataType="org.openhealthtools.mdht.emf.hl7.mif2.ShortDescriptiveName"
	 *        extendedMetaData="kind='attribute' name='name'"
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Render To Location</b></em>' attribute.
	 * The default value is <code>"false"</code>.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * If true, causes the specified item to be included as a link in its current location and rendered into the specified file location instead.
	 * UML: A tag on the PublicationItem stereotype
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Render To Location</em>' attribute.
	 * @see #isSetRenderToLocation()
	 * @see #unsetRenderToLocation()
	 * @see #setRenderToLocation(String)
	 * @see org.openhealthtools.mdht.emf.hl7.mif2.Mif2Package#getPublicationBase_RenderToLocation()
	 * @model default="false" unsettable="true" dataType="org.openhealthtools.mdht.emf.hl7.mif2.LocalFileReference"
	 *        extendedMetaData="kind='attribute' name='renderToLocation'"
	 * @generated
	 */
	String getRenderToLocation();

	/**
	 * Sets the value of the '{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getRenderToLocation <em>Render To Location</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Render To Location</em>' attribute.
	 * @see #isSetRenderToLocation()
	 * @see #unsetRenderToLocation()
	 * @see #getRenderToLocation()
	 * @generated
	 */
	void setRenderToLocation(String value);

	/**
	 * Unsets the value of the '{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getRenderToLocation <em>Render To Location</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isSetRenderToLocation()
	 * @see #getRenderToLocation()
	 * @see #setRenderToLocation(String)
	 * @generated
	 */
	void unsetRenderToLocation();

	/**
	 * Returns whether the value of the '{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getRenderToLocation <em>Render To Location</em>}' attribute is set.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return whether the value of the '<em>Render To Location</em>' attribute is set.
	 * @see #unsetRenderToLocation()
	 * @see #getRenderToLocation()
	 * @see #setRenderToLocation(String)
	 * @generated
	 */
	boolean isSetRenderToLocation();

	/**
	 * Returns the value of the '<em><b>Sort Key</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * A name used in determining the sort order of the model element within its siblings.
	 * Impl: This will usually be a sequential number, but could be something else.
	 * UML: tag value within ModelElement
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Sort Key</em>' attribute.
	 * @see #setSortKey(String)
	 * @see org.openhealthtools.mdht.emf.hl7.mif2.Mif2Package#getPublicationBase_SortKey()
	 * @model dataType="org.openhealthtools.mdht.emf.hl7.mif2.BasicFormalName"
	 *        extendedMetaData="kind='attribute' name='sortKey'"
	 * @generated
	 */
	String getSortKey();

	/**
	 * Sets the value of the '{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getSortKey <em>Sort Key</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Sort Key</em>' attribute.
	 * @see #getSortKey()
	 * @generated
	 */
	void setSortKey(String value);

	/**
	 * Returns the value of the '<em><b>Title</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * A descriptive label to be rendered when presenting the item
	 * UML: tag on the Publication Base stereotype
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Title</em>' attribute.
	 * @see #setTitle(String)
	 * @see org.openhealthtools.mdht.emf.hl7.mif2.Mif2Package#getPublicationBase_Title()
	 * @model dataType="org.openhealthtools.mdht.emf.hl7.mif2.ShortDescriptiveName"
	 *        extendedMetaData="kind='attribute' name='title'"
	 * @generated
	 */
	String getTitle();

	/**
	 * Sets the value of the '{@link org.openhealthtools.mdht.emf.hl7.mif2.PublicationBase#getTitle <em>Title</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Title</em>' attribute.
	 * @see #getTitle()
	 * @generated
	 */
	void setTitle(String value);

} // PublicationBase
