/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.openhealthtools.mdht.emf.hl7.mif2.CascadingAnnotationElementKind;
import org.openhealthtools.mdht.emf.hl7.mif2.DatatypeRef;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.AnnotationCascadeInfo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnnotationCascadeInfoValidator {
	boolean validate();

	boolean validateDatatype(DatatypeRef value);
	boolean validateClassifierName(String value);
	boolean validateClassifierNameExact(boolean value);
	boolean validateContextClassName(String value);
	boolean validateElementType(CascadingAnnotationElementKind value);
	boolean validateRimFeatureName(String value);
	boolean validateTargetClassName(String value);
	boolean validateTargetClassNameExact(boolean value);
}
