/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.ArtifactCrossReference;
import org.openhealthtools.mdht.emf.hl7.mif2.ElementDerivation;
import org.openhealthtools.mdht.emf.hl7.mif2.PackageOrArtifactRef;
import org.openhealthtools.mdht.emf.hl7.mif2.PackageRef;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.ArtifactCrossReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArtifactCrossReferenceValidator {
	boolean validate();

	boolean validateDerivedFrom(EList<ElementDerivation> value);
	boolean validateImportedPackage(EList<PackageRef> value);
	boolean validateDependentOnElement(EList<PackageOrArtifactRef> value);
	boolean validateContainedElements(EList<ArtifactCrossReference> value);
}
