/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import javax.xml.datatype.XMLGregorianCalendar;

import org.eclipse.emf.common.util.Enumerator;

import org.openhealthtools.mdht.emf.hl7.mif2.GroupVote;
import org.openhealthtools.mdht.emf.w3c.xhtml.Inline;


/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.BallotCommentResolution}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BallotCommentResolutionValidator {
	boolean validate();

	boolean validateResolutionComments(Inline value);
	boolean validateVote(GroupVote value);
	boolean validateResolution(Enumerator value);
	boolean validateResolutionDate(XMLGregorianCalendar value);
}
