/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.CMETEntryKind;
import org.openhealthtools.mdht.emf.hl7.mif2.PackageRef;
import org.openhealthtools.mdht.emf.hl7.mif2.SpecializationClass;
import org.openhealthtools.mdht.emf.hl7.mif2.StaticModelClassTemplateParameter;
import org.openhealthtools.mdht.emf.hl7.mif2.StaticModelInterfaceAnnotations;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.CommonModelElementDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CommonModelElementDefinitionValidator {
	boolean validate();

	boolean validateAnnotations(StaticModelInterfaceAnnotations value);
	boolean validateBoundStaticModel(PackageRef value);
	boolean validateTemplateParameter(EList<StaticModelClassTemplateParameter> value);
	boolean validateEntryClass(SpecializationClass value);
	boolean validateAttributionLevel(Object value);
	boolean validateEntryKind(CMETEntryKind value);
	boolean validateName(String value);
	boolean validateOtherClassName(String value);
}
