/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.openhealthtools.mdht.emf.hl7.mif2.DerivationRelationshipKind;
import org.openhealthtools.mdht.emf.w3c.xhtml.Flow;


/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.Derivation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DerivationValidator {
	boolean validate();

	boolean validateReason(Flow value);
	boolean validateAnnotationsReviewedBy(String value);
	boolean validateAreAnnotationsReviewed(boolean value);
	boolean validateRelationship(DerivationRelationshipKind value);
}
