/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EMap;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.openhealthtools.mdht.emf.hl7.mif2.ComplexMarkupWithLanguage;
import org.openhealthtools.mdht.emf.hl7.mif2.DerivedStaticModelsType;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalApplicationRole;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalArtifactXRefSummary;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalCodeSystem;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalCodeSystemSupplement;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalConformanceProfile;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalDatatypeModelLibrary;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalDerivedStaticModel;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalDomainAnalysisModel;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalDomainInstanceExample;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalFreehandDocument;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalGenericPackage;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalGlossary;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalInteraction;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalInteractionProfile;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalMifChanges;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalPublicationPackage;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalSerializedStaticModel;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalStaticModel;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalStaticModelInterfacePackage;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalStoryboard;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalStructuredDocument;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalTestScenario;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalTriggerEvent;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalValueSet;
import org.openhealthtools.mdht.emf.hl7.mif2.GlobalVocabularyModel;
import org.openhealthtools.mdht.emf.hl7.mif2.SerializedStaticModelsType;
import org.openhealthtools.mdht.emf.hl7.mif2.StaticModelsType;
import org.openhealthtools.mdht.emf.w3c.xhtml.Flow;
import org.openhealthtools.mdht.emf.w3c.xhtml.Inline;


/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.DocumentRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateXMLNSPrefixMap(EMap<String, String> value);
	boolean validateXSISchemaLocation(EMap<String, String> value);
	boolean validateApplicationRole(GlobalApplicationRole value);
	boolean validateArtifactXrefSummary(GlobalArtifactXRefSummary value);
	boolean validateCodeSystem(GlobalCodeSystem value);
	boolean validateCodeSystemSupplement(GlobalCodeSystemSupplement value);
	boolean validateConformanceProfile(GlobalConformanceProfile value);
	boolean validateDatatypeModelLibrary(GlobalDatatypeModelLibrary value);
	boolean validateDerivedStaticModel(GlobalDerivedStaticModel value);
	boolean validateDerivedStaticModels(DerivedStaticModelsType value);
	boolean validateDomainAnalysisModel(GlobalDomainAnalysisModel value);
	boolean validateDomainInstanceExample(GlobalDomainInstanceExample value);
	boolean validateFreehandDocument(GlobalFreehandDocument value);
	boolean validateGlossary(GlobalGlossary value);
	boolean validateInteraction(GlobalInteraction value);
	boolean validateInteractionProfile(GlobalInteractionProfile value);
	boolean validateMifChanges(GlobalMifChanges value);
	boolean validatePackage(GlobalGenericPackage value);
	boolean validatePublication(GlobalPublicationPackage value);
	boolean validateSerializedStaticModel(GlobalSerializedStaticModel value);
	boolean validateSerializedStaticModels(SerializedStaticModelsType value);
	boolean validateStaticModel(GlobalStaticModel value);
	boolean validateStaticModelInterfacePackage(GlobalStaticModelInterfacePackage value);
	boolean validateStaticModels(StaticModelsType value);
	boolean validateStoryboard(GlobalStoryboard value);
	boolean validateStructuredDocument(GlobalStructuredDocument value);
	boolean validateTestScenario(GlobalTestScenario value);
	boolean validateTriggerEvent(GlobalTriggerEvent value);
	boolean validateTxtComplex(Flow value);
	boolean validateTxtComplexWithLanguage(ComplexMarkupWithLanguage value);
	boolean validateTxtInlineOnly(Inline value);
	boolean validateValueSet(GlobalValueSet value);
	boolean validateVocabularyModel(GlobalVocabularyModel value);
}
