/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import java.math.BigInteger;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.openhealthtools.mdht.emf.hl7.mif2.AttributeValueRef;
import org.openhealthtools.mdht.emf.hl7.mif2.ElementValueRef;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.ElementRef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ElementRefValidator {
	boolean validate();

	boolean validateContextRef(FeatureMap value);
	boolean validateContextElement(EList<ElementValueRef> value);
	boolean validateContextAttribute(EList<AttributeValueRef> value);
	boolean validateName(String value);
	boolean validateRepetition(BigInteger value);
}
