/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import java.math.BigInteger;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.ConformanceKind;
import org.openhealthtools.mdht.emf.hl7.mif2.DefaultDeterminerKind;
import org.openhealthtools.mdht.emf.hl7.mif2.RangeDefinition;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.Feature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FeatureValidator {
	boolean validate();

	boolean validateEnumerationValue(EList<String> value);
	boolean validateAllowedRange(EList<RangeDefinition> value);
	boolean validateConformance(ConformanceKind value);
	boolean validateDefaultFrom(DefaultDeterminerKind value);
	boolean validateDefaultValue(String value);
	boolean validateFixedValue(String value);
	boolean validateIsMandatory(boolean value);
	boolean validateMaximumLength(BigInteger value);
	boolean validateMinimumLength(BigInteger value);
}
