/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import java.math.BigInteger;

import java.util.List;

import org.openhealthtools.mdht.emf.w3c.xhtml.Flow;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.Legalese}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LegaleseValidator {
	boolean validate();

	boolean validateNotation(Flow value);
	boolean validateDisclaimer(Flow value);
	boolean validateLicenseTerms(Flow value);
	boolean validateVersioningPolicy(Flow value);
	boolean validateCopyrightOwner(String value);
	boolean validateCopyrightYears(List<BigInteger> value);
}
