/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.openhealthtools.mdht.emf.hl7.mif2.ElementChange;
import org.openhealthtools.mdht.emf.hl7.mif2.PackageOrArtifactRef;
import org.openhealthtools.mdht.emf.hl7.mif2.RenderingInformation;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.MifChanges}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MifChangesValidator {
	boolean validate();

	boolean validateRenderingInformation(RenderingInformation value);
	boolean validateOriginalArtifact(PackageOrArtifactRef value);
	boolean validateRevisedArtifact(PackageOrArtifactRef value);
	boolean validateChange(ElementChange value);
}
