/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.DatatypeLimitation;
import org.openhealthtools.mdht.emf.hl7.mif2.DatatypeModelLibrary;
import org.openhealthtools.mdht.emf.hl7.mif2.ModelConformanceKind;
import org.openhealthtools.mdht.emf.hl7.mif2.PackageRef;
import org.openhealthtools.mdht.emf.hl7.mif2.StaticModelAnnotations;
import org.openhealthtools.mdht.emf.hl7.mif2.StaticModelDerivation;
import org.openhealthtools.mdht.emf.hl7.mif2.StaticModelDerivationSource;
import org.openhealthtools.mdht.emf.hl7.mif2.StaticModelRepresentationKind;
import org.openhealthtools.mdht.emf.hl7.mif2.StaticPackageDiagramGraphicInformation;
import org.openhealthtools.mdht.emf.hl7.mif2.SubjectAreaPackage;
import org.openhealthtools.mdht.emf.hl7.mif2.VocabularyCodeRef;
import org.openhealthtools.mdht.emf.hl7.mif2.VocabularyLimitation;
import org.openhealthtools.mdht.emf.hl7.mif2.VocabularyModel;
import org.openhealthtools.mdht.emf.w3c.xhtml.Img;


/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.StaticModelBase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StaticModelBaseValidator {
	boolean validate();

	boolean validateAnnotations(StaticModelAnnotations value);
	boolean validateGraphicRepresentation(EList<StaticPackageDiagramGraphicInformation> value);
	boolean validateFigure(Img value);
	boolean validateDerivedFrom(EList<StaticModelDerivation> value);
	boolean validateHasDerivations(StaticModelDerivationSource value);
	boolean validateImportedDatatypeModelPackage(PackageRef value);
	boolean validateImportedVocabularyModelPackage(PackageRef value);
	boolean validateImportedCommonModelElementPackage(PackageRef value);
	boolean validateImportedStubPackage(PackageRef value);
	boolean validateImportAnnotationLibrary(PackageRef value);
	boolean validateAdditionalDatatypeModel(EList<DatatypeModelLibrary> value);
	boolean validateDatatypeLimitation(EList<DatatypeLimitation> value);
	boolean validateAdditionalVocabularyModel(EList<VocabularyModel> value);
	boolean validateVocabularyLimitation(EList<VocabularyLimitation> value);
	boolean validateSubjectAreaPackage(EList<SubjectAreaPackage> value);
	boolean validateDefinitionalCode(EList<VocabularyCodeRef> value);
	boolean validateConformanceLevel(ModelConformanceKind value);
	boolean validateIsAbstract(boolean value);
	boolean validateIsSerializable(boolean value);
	boolean validateRepresentationKind(StaticModelRepresentationKind value);
}
