/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.BusinessName;
import org.openhealthtools.mdht.emf.hl7.mif2.ValueSetAnnotations;
import org.openhealthtools.mdht.emf.hl7.mif2.ValueSetVersion;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.ValueSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValueSetValidator {
	boolean validate();

	boolean validateBusinessName(EList<BusinessName> value);
	boolean validateAnnotations(ValueSetAnnotations value);
	boolean validateVersion(EList<ValueSetVersion> value);
	boolean validateId(String value);
	boolean validateIsImmutable(boolean value);
	boolean validateName(String value);
	boolean validateSortKey(String value);
}
