/*******************************************************************************
 * Copyright (c) 2006, 2009 David A Carlson
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     David A Carlson (XMLmodeling.com) - initial API and implementation
 *******************************************************************************/
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.ConformanceProfileAnnotations;
import org.openhealthtools.mdht.emf.hl7.mif2.ConformanceTriggerEvents;
import org.openhealthtools.mdht.emf.hl7.mif2.DocumentProfile;
import org.openhealthtools.mdht.emf.hl7.mif2.ImplementationMessageConstraints;
import org.openhealthtools.mdht.emf.hl7.mif2.InteractionProfile;
import org.openhealthtools.mdht.emf.hl7.mif2.PackageRef;
import org.openhealthtools.mdht.emf.hl7.mif2.Storyboard;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.ConformanceProfile}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConformanceProfileValidator {
	boolean validate();

	boolean validateAnnotations(ConformanceProfileAnnotations value);

	boolean validateStoryboards(EList<Storyboard> value);

	boolean validateImplementationConstraints(ImplementationMessageConstraints value);

	boolean validateSupportedApplicationRoles(EList<PackageRef> value);

	boolean validateSupportedTriggerEvents(EList<ConformanceTriggerEvents> value);

	boolean validateSupportedAppRoleInteractions(EList<InteractionProfile> value);

	boolean validateUnsupportedAppRoleInteractions(EList<PackageRef> value);

	boolean validateExtraInteractions(EList<InteractionProfile> value);

	boolean validateSupportedAppRoleDocuments(EList<DocumentProfile> value);

	boolean validateUnsupportedAppRoleDocuments(EList<PackageRef> value);

	boolean validateExtraDocuments(EList<DocumentProfile> value);
}
