/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import java.math.BigInteger;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.ComplexMarkupWithLanguage;
import org.openhealthtools.mdht.emf.hl7.mif2.DurationUnitsKind;
import org.openhealthtools.mdht.emf.hl7.mif2.PackageRef;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.ImplementationMessageConstraints}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImplementationMessageConstraintsValidator {
	boolean validate();

	boolean validateSupportedTransport(EList<PackageRef> value);
	boolean validateTimingBackground(ComplexMarkupWithLanguage value);
	boolean validateExpectedResponseTime(DurationUnitsKind value);
	boolean validateRetryTime(DurationUnitsKind value);
	boolean validateMaximumRetryCount(BigInteger value);
}
