<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ccd"
    nsURI="http://www.openhealthtools.org/mdht/uml/cda/ccd" nsPrefix="ccd">
  <eClassifiers xsi:type="ecore:EClass" name="ProblemAct" eSuperTypes="../../org.openhealthtools.mdht.uml.cda/model/cda.ecore#//Act">
    <eAnnotations source="http://www.openhealthtools.org/mdht/uml/cda/annotation">
      <details key="templateId.root" value="2.16.840.1.113883.10.20.1.27"/>
    </eAnnotations>
    <eOperations name="templateId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/uml2/1.1.0/GenModel">
        <details key="body" value="self.templateId->exists(id : datatypes::II | id.root = '2.16.840.1.113883.10.20.1.27')"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.templateId->exists(id : datatypes::II | id.root = '2.16.840.1.113883.10.20.1.27')"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="init" ordered="false" lowerBound="1" eType="#//ProblemAct">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="org.openhealthtools.mdht.uml.cda.util.CDAUtil.addTemplateIds(this);&#xD;&#xA;return this;"/>
        <details key="body" value="org.openhealthtools.mdht.uml.cda.util.CDAUtil.addTemplateIds(this);&#xD;&#xA;return this;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProblemObservation" eSuperTypes="../../org.openhealthtools.mdht.uml.cda/model/cda.ecore#//Observation">
    <eAnnotations source="http://www.openhealthtools.org/mdht/uml/cda/annotation">
      <details key="templateId.root" value="2.16.840.1.113883.10.20.1.28"/>
    </eAnnotations>
    <eOperations name="templateId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/uml2/1.1.0/GenModel">
        <details key="body" value="self.templateId->exists(id : datatypes::II | id.root = '2.16.840.1.113883.10.20.1.28')"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.templateId->exists(id : datatypes::II | id.root = '2.16.840.1.113883.10.20.1.28')"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="init" ordered="false" lowerBound="1" eType="#//ProblemObservation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="org.openhealthtools.mdht.uml.cda.util.CDAUtil.addTemplateIds(this);&#xD;&#xA;return this;"/>
        <details key="body" value="org.openhealthtools.mdht.uml.cda.util.CDAUtil.addTemplateIds(this);&#xD;&#xA;return this;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="#//ProblemAct">
    <eAnnotations source="http://www.openhealthtools.org/mdht/uml/cda/annotation">
      <details key="templateId.root" value="1.2.3"/>
    </eAnnotations>
    <eOperations name="init" ordered="false" lowerBound="1" eType="#//A">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="org.openhealthtools.mdht.uml.cda.util.CDAUtil.addTemplateIds(this);&#xD;&#xA;return this;"/>
        <details key="body" value="org.openhealthtools.mdht.uml.cda.util.CDAUtil.addTemplateIds(this);&#xD;&#xA;return this;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="#//A">
    <eAnnotations source="http://www.openhealthtools.org/mdht/uml/cda/annotation">
      <details key="templateId.root" value="4.5.6"/>
    </eAnnotations>
    <eOperations name="init" ordered="false" lowerBound="1" eType="#//B">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="org.openhealthtools.mdht.uml.cda.util.CDAUtil.addTemplateIds(this);&#xD;&#xA;return this;"/>
        <details key="body" value="org.openhealthtools.mdht.uml.cda.util.CDAUtil.addTemplateIds(this);&#xD;&#xA;return this;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C" eSuperTypes="#//B">
    <eAnnotations source="http://www.openhealthtools.org/mdht/uml/cda/annotation">
      <details key="templateId.root" value="7.8.9"/>
    </eAnnotations>
    <eOperations name="init" ordered="false" lowerBound="1" eType="#//C">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="org.openhealthtools.mdht.uml.cda.util.CDAUtil.addTemplateIds(this);&#xD;&#xA;return this;"/>
        <details key="body" value="org.openhealthtools.mdht.uml.cda.util.CDAUtil.addTemplateIds(this);&#xD;&#xA;return this;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
