/*******************************************************************************
 * Copyright (c) 2006, 2009 David A Carlson
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     David A Carlson (XMLmodeling.com) - initial API and implementation
 *******************************************************************************/
package org.openhealthtools.mdht.emf.hl7.mif2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.mdht.emf.hl7.mif2.ContentDefinition;
import org.openhealthtools.mdht.emf.hl7.mif2.IncludeRelatedCodes;

/**
 * A sample validator interface for {@link org.openhealthtools.mdht.emf.hl7.mif2.CodeBasedContentDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CodeBasedContentDefinitionValidator {
	boolean validate();

	boolean validateHeadCodes(ContentDefinition value);

	boolean validateIncludeRelatedCodes(EList<IncludeRelatedCodes> value);

	boolean validateCode(String value);

	boolean validateIncludeHeadCode(boolean value);
}
